name = "PPtools"
uuid = "e1b1bdea-ab6f-4625-99f5-b548e5d5aff1"
authors = ["Steve Harris <git@steveharris.me> and contributors"]
version = "1.0.0-DEV"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
Formatting = "0.4.3"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
